import importlib.util
import os
import subprocess
import tempfile
import unittest
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
SCRIPT = REPO / "bin" / "authorship-gate.py"


def load_gate():
    spec = importlib.util.spec_from_file_location("authorship_gate", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class AuthorshipGateTest(unittest.TestCase):
    def setUp(self):
        self.gate = load_gate()
        self.tmp = tempfile.TemporaryDirectory()
        self.repo = Path(self.tmp.name)
        subprocess.run(["git", "init", "-q", "-b", "main"], cwd=self.repo, check=True)
        self.base = self.commit("Creator", "creator@example.test", "base")

    def tearDown(self):
        self.tmp.cleanup()

    def commit(self, name, email, message):
        marker = self.repo / "marker"
        marker.write_text(message + "\n", encoding="utf-8")
        subprocess.run(["git", "add", "marker"], cwd=self.repo, check=True)
        env = {
            **os.environ,
            "GIT_AUTHOR_NAME": name,
            "GIT_AUTHOR_EMAIL": email,
            "GIT_COMMITTER_NAME": name,
            "GIT_COMMITTER_EMAIL": email,
        }
        subprocess.run(
            ["git", "commit", "-q", "--no-gpg-sign", "-m", message],
            cwd=self.repo,
            env=env,
            check=True,
        )
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=self.repo,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()

    def inspect(self, head):
        previous = Path.cwd()
        try:
            os.chdir(self.repo)
            return self.gate.inspect_range(self.base, head)
        finally:
            os.chdir(previous)

    def test_shoggoth_agent_author_is_allowed(self):
        head = self.commit("Shoggoth", "shoggoth@wildcat.finance", "agent work")
        self.assertEqual(self.inspect(head), [head])

    def test_human_contributor_keeps_authorship(self):
        head = self.commit("External Contributor", "human@example.test", "human work")
        self.assertEqual(self.inspect(head), [head])

    def test_claude_author_is_refused(self):
        head = self.commit("Claude", "noreply@anthropic.com", "agent work")
        with self.assertRaisesRegex(self.gate.GateError, "runtime host as author"):
            self.inspect(head)

    def test_codex_coauthor_is_refused(self):
        head = self.commit(
            "Shoggoth",
            "shoggoth@wildcat.finance",
            "agent work\n\nCo-authored-by: Codex <noreply@openai.com>",
        )
        with self.assertRaisesRegex(self.gate.GateError, "runtime host as co-author"):
            self.inspect(head)

    def test_runtime_generated_by_footer_is_refused(self):
        head = self.commit(
            "Shoggoth",
            "shoggoth@wildcat.finance",
            "agent work\n\nGenerated by Claude Code",
        )
        with self.assertRaisesRegex(self.gate.GateError, "runtime-host byline"):
            self.inspect(head)

    def test_human_generated_by_link_is_not_reclassified_as_a_host(self):
        head = self.commit(
            "External Contributor",
            "human@example.test",
            "human work\n\nGenerated by [External Contributor](https://example.test)",
        )
        self.assertEqual(self.inspect(head), [head])

    def test_unsafe_ref_is_refused_before_git(self):
        with self.assertRaisesRegex(self.gate.GateError, "not a safe Git ref"):
            self.gate.checked_ref("--upload-pack=anything", "head")


if __name__ == "__main__":
    unittest.main()
